name: testoblog
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  another_carousel_pro: ^1.0.2
  mailer: ^6.1.0
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  webview_flutter: ^4.7.0
  flutter_html: ^3.0.0-beta.2
  flutter_custom_cards: ^0.2.1
  easy_url_launcher: ^0.0.5
  provider: ^6.1.2
  flutter_native_splash: ^2.4.0
  rename: ^3.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
flutter_native_splash:
  image: images/madrassa.png
  color: "#42a5f5"
  android: true
  
